# Generated by Django 4.2.3 on 2023-08-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_AD', '0002_alter_ad_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
