# Generated by Django 4.2.3 on 2023-08-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_AD', '0004_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to='ads/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
